/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class enroll extends javax.swing.JPanel {
Connection con;
    /**
     * Creates new form enroll
     */
    public enroll() {
        initComponents();
        DBconnection c= new DBconnection();
        con=c.getconnection();
       show_undergraduate();
       show_postergraduate();
    }
    
    
    
public void clear(){

studentid.setText("");
nic.setText("");
fullname.setText("");
initial.setText("");
jCombocourse.setSelectedItem("None");
jComboduration.setSelectedItem("None");
batch.setText("");
jCombobatch.setSelectedItem("None");
ugraduatefee.setText("");
studentid1.setText("");
nic1.setText("");
fullname1.setText("");
initial1.setText("");
jCombocourse1.setSelectedItem("None");
jComboduration1.setSelectedItem("None");
batch1.setText("");
jCombobatch1.setSelectedItem("None");
ugraduatefee1.setText("");

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCombocourse = new javax.swing.JComboBox<>();
        fullname = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboduration = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jCombobatch = new javax.swing.JComboBox<>();
        initial = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ugraduatefee = new javax.swing.JTextField();
        jButton3save1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        batch = new datechooser.beans.DateChooserCombo();
        jTextField3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        studentid1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        nic1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        initial1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCombocourse1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboduration1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jCombobatch1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        ugraduatefee1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        batch1 = new datechooser.beans.DateChooserCombo();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("                                                          STUDENT ENROLLMENT FOR COURSES");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 70));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Student Id");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NID/Passport");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Full name");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("     Course Name");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 230, 30));

        jCombocourse.setBackground(new java.awt.Color(255, 255, 255));
        jCombocourse.setForeground(new java.awt.Color(0, 0, 0));
        jCombocourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "advanceJAVA", "advancephp", "advanceC++", "advaceC#" }));
        jCombocourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jCombocourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 270, 30));

        fullname.setEditable(false);
        fullname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 270, 30));

        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        jPanel5.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, 30));

        studentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentidKeyReleased(evt);
            }
        });
        jPanel5.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 270, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("            Duration");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 230, 30));

        jComboduration.setBackground(new java.awt.Color(255, 255, 255));
        jComboduration.setForeground(new java.awt.Color(0, 0, 0));
        jComboduration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1 Years part time", "1 Years Full time" }));
        jComboduration.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jComboduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 270, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Date");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 60, 30));

        jCombobatch.setBackground(new java.awt.Color(255, 255, 255));
        jCombobatch.setForeground(new java.awt.Color(0, 0, 0));
        jCombobatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", " ", "Monday8.00 am to 5.00 pm", "Tustady8.00 am to 5.00 pm", "fridays8.00 am to 5.00 pm", "Sunday8.00 am to 5.00 pm", "Saturday8.00 am to 5.00 pm", "Weekdays8.00 am to 5.00 pm" }));
        jCombobatch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jCombobatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 220, 30));

        initial.setEditable(false);
        initial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 270, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Other Name");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("     Course Fee");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 230, 30));

        ugraduatefee.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(ugraduatefee, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 270, 30));

        jButton3save1.setBackground(new java.awt.Color(255, 255, 255));
        jButton3save1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3save1.setForeground(new java.awt.Color(51, 0, 255));
        jButton3save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Save-as-icon.png"))); // NOI18N
        jButton3save1.setText("Save");
        jButton3save1.setAutoscrolls(true);
        jButton3save1.setOpaque(false);
        jButton3save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3save1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Text-Edit-icon.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Close-2-icon.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 210, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("To search or delete individual type the student number in student uni id field");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 650, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Actions-edit-clear-icon.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 200, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 110, -1, 28));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("Day");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 110, 50, 30));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 560, 210));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "NID/Password", "Fullname", "Initials", "Course Name", "Duration", "DATE.", "Day and time", "coursefee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1100, 180));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Day");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, 30));

        jTabbedPane1.addTab("Poster Graduate", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(51, 0, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Text-Edit-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 210, 60));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("        Studenti Id");
        jLabel27.setToolTipText("");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 30));

        studentid1.setBackground(new java.awt.Color(255, 255, 255));
        studentid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentid1KeyReleased(evt);
            }
        });
        jPanel4.add(studentid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("     Nic/Passport N°");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 30));

        nic1.setBackground(new java.awt.Color(255, 255, 255));
        nic1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nic1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nic1KeyReleased(evt);
            }
        });
        jPanel4.add(nic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 270, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("       Full name");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 30));

        fullname1.setEditable(false);
        fullname1.setBackground(new java.awt.Color(255, 255, 255));
        fullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname1ActionPerformed(evt);
            }
        });
        jPanel4.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 270, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("       Other Name");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 30));

        initial1.setEditable(false);
        initial1.setBackground(new java.awt.Color(255, 255, 255));
        initial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initial1ActionPerformed(evt);
            }
        });
        jPanel4.add(initial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText(" Course Enrolling");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 210, 30));

        jCombocourse1.setBackground(new java.awt.Color(255, 255, 255));
        jCombocourse1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jCombocourse1.setForeground(new java.awt.Color(0, 0, 0));
        jCombocourse1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "JAVA", "C#", "PHP", "C++", "IONIC" }));
        jCombocourse1.setOpaque(false);
        jPanel4.add(jCombocourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 270, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Duration");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 210, 30));

        jComboduration1.setBackground(new java.awt.Color(255, 255, 255));
        jComboduration1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jComboduration1.setForeground(new java.awt.Color(0, 0, 0));
        jComboduration1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2 Years part time", "2 Years Full time" }));
        jPanel4.add(jComboduration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Date");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 60, 30));

        jCombobatch1.setBackground(new java.awt.Color(255, 255, 255));
        jCombobatch1.setForeground(new java.awt.Color(0, 0, 0));
        jCombobatch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sunday 8.00 am to 5.00 pm", "Saturday  8.00 am to 5.00 pm", "Weekdays 8.00 am to 5.00 pm(" }));
        jCombobatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombobatch1ActionPerformed(evt);
            }
        });
        jPanel4.add(jCombobatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 230, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Course Fee");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 210, 30));

        ugraduatefee1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(ugraduatefee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 270, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("To search or delete individual enrollment type the student number in student uni id field");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 640, -1));

        jButton3save.setBackground(new java.awt.Color(255, 255, 255));
        jButton3save.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3save.setForeground(new java.awt.Color(0, 102, 102));
        jButton3save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Save-as-icon.png"))); // NOI18N
        jButton3save.setText("Save");
        jButton3save.setAutoscrolls(true);
        jButton3save.setOpaque(false);
        jButton3save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3saveActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Actions-edit-clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 220, 60));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Close-2-icon.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 220, 60));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "NID/Password", "Fullname", "Initials", "Course Name", "Duration", "DATE", "Day and time", "coursefee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1100, 200));
        jPanel4.add(batch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 100, 140, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Day");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, 30));

        jTabbedPane1.addTab("Under Graduate Program", jPanel4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1110, 530));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased

        try {
           
            String query = "SELECT * FROM student WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("fullname");
                fullname.setText(add1);
                String add2 = rs.getString("initial");
                initial.setText(add2);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_nicKeyReleased

    private void jButton3save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3save1ActionPerformed
      try {
          
           
            String query = "INSERT INTO courseposter(nic,studentid,fullname,initials,course,duration,batchno,day,coursefee) values(?,?,?,?,?,?,?,?,?)";
            String query1 = "SELECT * FROM courseunder WHERE nic=?";
            PreparedStatement pst1 = con.prepareStatement(query1);
            pst1.setString(1, nic.getText());
            ResultSet rs = pst1.executeQuery();
            if (rs.next()) {
                
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"This student has already enrolled for a Poster Graduate Program","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            
            }
            
            
            
              
            PreparedStatement pst = con.prepareStatement(query);
            
            
             if (nic.getText().isEmpty() | studentid.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|jCombocourse.getSelectedItem().toString().equals("None")|jComboduration.getSelectedItem().toString().equals("None")|batch.getText().isEmpty()||jCombobatch.getSelectedItem().equals("None")) {
               
                 getToolkit().beep();
                JOptionPane.showMessageDialog(null,"One of the required field is empty","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
             
            
             
             
             else{
            pst.setString(1, nic.getText()); 
            pst.setString(2, studentid.getText());
            pst.setString(3, fullname.getText());
            pst.setString(4, initial.getText());
            pst.setString(5, jCombocourse.getSelectedItem().toString());
            pst.setString(6, jComboduration.getSelectedItem().toString());
          
            pst.setString(7, batch.getText());
            pst.setString(8, jCombobatch.getSelectedItem().toString());
            pst.setString(9, ugraduatefee.getText());
            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
            model.setRowCount(0);
           show_postergraduate();
            JOptionPane.showMessageDialog(null, "Saved Successfully");
             }
            
            
            
            
            
            
            
            
           
          
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
     
    }//GEN-LAST:event_jButton3save1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (nic.getText().isEmpty() | studentid.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|jCombocourse.getSelectedItem().toString().equals("None")|jComboduration.getSelectedItem().toString().equals("None")|batch.getText().isEmpty()||jCombobatch.getSelectedItem().equals("None")) {
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Specify What Data You Want To Update","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }
        else{
        try {
          
            String value=nic.getText();
            String query = "UPDATE courseposter SET studentid=?,fullname=?,initials=?,course=?,duration=?,batchno=?,day=?,coursefee=? WHERE nic='"+value+"'";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, studentid.getText());
            pst.setString(2, fullname.getText());
            pst.setString(3, initial.getText());

            pst.setString(4, jCombocourse.getSelectedItem().toString());
            pst.setString(5, jComboduration.getSelectedItem().toString());
           
            pst.setString(6, batch.getText());
             pst.setString(7, jCombobatch.getSelectedItem().toString());
            pst.setString(8, ugraduatefee.getText());
            

            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
            model.setRowCount(0);
             show_postergraduate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         
        if (studentid.getText().isEmpty()) {
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Enter the Studentid in the Studentid Field to Delete Data","ERROR",JOptionPane.ERROR_MESSAGE,null);
            
        }
        else{
        try {
             int p= JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Student "+fullname.getText()+" From The Database","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0) {
          
            String query = "DELETE FROM courseposter WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic.getText());
            pst.execute();
            DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
            model.setRowCount(0);
     show_postergraduate();
            JOptionPane.showMessageDialog(null, "data successfully deleted");
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        }
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void studentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentidKeyReleased
  try {
          
            String query = "SELECT * FROM courseposter WHERE studentid=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentid.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("nic");
                nic.setText(add1);
                String add2 = rs.getString("fullname");
                fullname.setText(add2);
                String add3 = rs.getString("initials");
                initial.setText(add3);
                String add4 = rs.getString("course");
                jCombocourse.setSelectedItem(add4);
                String add5 = rs.getString("duration");
                jComboduration.setSelectedItem(add5);
                String add6 = rs.getString("batchno");
                batch.setText(add6);
                String add7 = rs.getString("day");
                jCombobatch.setSelectedItem(add7);
                String add8 = rs.getString("coursefee");
                ugraduatefee.setText(add8);
            
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
        
    }//GEN-LAST:event_studentidKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
          String s=nic.getText();
            
            if (!(s.length()<10 ))
            {
                
                    evt.consume();
                      getToolkit().beep();
            
            }
    }//GEN-LAST:event_nicKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (studentid1.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Enter the Studentid in the Studentid Field to Delete Data","ERROR",JOptionPane.ERROR_MESSAGE,null);

        } else{

            try {
                int p= JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Student "+fullname1.getText()+" From The Database","Delete",JOptionPane.YES_NO_OPTION);
                if (p==0) {

                    String query = "DELETE FROM courseunder WHERE studentid=?";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setString(1, studentid1.getText());
                    pst.execute();
                     DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
            model.setRowCount(0);
            show_undergraduate();
                    JOptionPane.showMessageDialog(null, "data successfully deleted");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
            
        }
       // show_undergraduate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3saveActionPerformed
         
        if (studentid1.getText().isEmpty()|nic1.getText().isEmpty()|fullname1.getText().isEmpty()|initial1.getText().isEmpty()|jCombocourse1.getSelectedItem().equals("None")|jComboduration1.getSelectedItem().equals("None")|batch1.getText().isEmpty()|jCombobatch1.getSelectedItem().equals("None")|ugraduatefee1.getText().isEmpty()) {

            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"One of the required field is empty","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }
               else{
            try {

                String query = "INSERT INTO courseunder (nic,studentid,fullname,initials,course,duration,batchno,day,coursefee) values(?,?,?,?,?,?,?,?,?)";
                String query1 = "SELECT * FROM courseposter WHERE nic=?";
                PreparedStatement pst1 = con.prepareStatement(query1);
                pst1.setString(1, nic1.getText());
                ResultSet rs = pst1.executeQuery();
                if (rs.next()) {

                    getToolkit().beep();
                    JOptionPane.showMessageDialog(null,"This student has already enrolled for a Poster Graduate Program","ERROR",JOptionPane.ERROR_MESSAGE,null);

                }
                else{

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, nic1.getText());
                    pst.setString(2, studentid1.getText());
                    pst.setString(3, fullname1.getText());
                    pst.setString(4, initial1.getText());
                    pst.setString(5, jCombocourse1.getSelectedItem().toString());
                    pst.setString(6, jComboduration1.getSelectedItem().toString());

                    pst.setString(7, batch1.getText());
                    pst.setString(8, jCombobatch1.getSelectedItem().toString());
                    pst.setString(9, ugraduatefee1.getText());
                    pst.executeUpdate();
                    DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
            model.setRowCount(0);
            show_undergraduate();
                    
                    JOptionPane.showMessageDialog(null, "Saved Successfully");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
        show_undergraduate();
         
    }//GEN-LAST:event_jButton3saveActionPerformed

    private void nic1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic1KeyTyped
        String s=nic1.getText();

        if (!(s.length()<10 ))
        {

            evt.consume();
            getToolkit().beep();

        }
    }//GEN-LAST:event_nic1KeyTyped

    private void nic1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nic1KeyReleased
        try {

            String query = "SELECT * FROM student WHERE nic=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nic1.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("fullname");
                fullname1.setText(add1);
                String add2 = rs.getString("initial");
                initial1.setText(add2);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_nic1KeyReleased

    private void studentid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentid1KeyReleased
        try {

            String query = "SELECT * FROM courseunder WHERE studentid=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, studentid1.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("nic");
                nic1.setText(add1);
                String add2 = rs.getString("fullname");
                fullname1.setText(add2);
                String add3 = rs.getString("initials");
                initial1.setText(add3);
                String add4 = rs.getString("course");
                jCombocourse1.setSelectedItem(add4);
                String add5 = rs.getString("duration");
                jComboduration1.setSelectedItem(add5);
                String add6 = rs.getString("batchno");
                batch1.setText(add6);
                String add7 = rs.getString("day");
                jCombobatch1.setSelectedItem(add7);
                String add8 = rs.getString("coursefee");
                ugraduatefee1.setText(add8);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_studentid1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (studentid1.getText().isEmpty()|nic1.getText().isEmpty()|fullname1.getText().isEmpty()|initial1.getText().isEmpty()|jCombocourse1.getSelectedItem().equals("None")|jComboduration1.getSelectedItem().equals("None")|batch1.getText().isEmpty()|jCombobatch1.getSelectedItem().equals("None")|ugraduatefee1.getText().isEmpty()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Please Specify What Data You Want To Update","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }

        else{
            try {

                String value=nic1.getText();
                String query = "UPDATE courseunder SET studentid=?,fullname=?,initials=?,course=?,duration=?,batchno=?,day=?,coursefee=? WHERE nic='"+value+"'";
                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, studentid1.getText());
                pst.setString(2, fullname1.getText());
                pst.setString(3, initial1.getText());

                pst.setString(4, jCombocourse1.getSelectedItem().toString());
                pst.setString(5, jComboduration1.getSelectedItem().toString());

                pst.setString(6, batch1.getText());
                pst.setString(7, jCombobatch1.getSelectedItem().toString());
                pst.setString(8, ugraduatefee1.getText());

                pst.executeUpdate();
                 DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
            model.setRowCount(0);
            show_undergraduate();
                JOptionPane.showMessageDialog(null, "Updated Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullname1ActionPerformed

    private void initial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initial1ActionPerformed

    private void jCombobatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombobatch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombobatch1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    
public void show_undergraduate()
    {
        try {
            
            DefaultTableModel tb=(DefaultTableModel)jTable4.getModel();
             //DefaultTableModel tb=(DefaultTableModel)jTable4.getModel();
             tb.fireTableDataChanged();
             tb.setRowCount(0);

          
            Statement st=con.createStatement();
            
             ResultSet r=st.executeQuery("SELECT * FROM courseunder ");  
            
             
              while(r.next()){
                     
                     Vector v=new Vector();
                     
                     String studentid =(r.getString("studentid"));
                     String nic=(r.getString("nic"));
                     String fullname=(r.getString("fullname"));
                     String initial=(r.getString("initials"));
                     String course=(r.getString("course"));
                     String duration=(r.getString("duration"));
                     String batchno=(r.getString("batchno"));
                     String day=(r.getString("day"));
                     String coursefee=(r.getString("coursefee"));
                     
                     
                     v.add(studentid);
                     v.add(nic);
                     v.add(fullname);
                     v.add(initial);
                     v.add(course);
                     v.add(duration);
                     v.add(batchno);
                     v.add(day);
                     v.add(coursefee);
                    
                  tb.addRow(v);
              }
            
        } catch (Exception e) {
        }
    
    }
    
    
    public void show_postergraduate(){
    
    try {
            
            DefaultTableModel tb=(DefaultTableModel)jTable3.getModel();
             
          
            Statement st=con.createStatement();
            
             ResultSet r=st.executeQuery("SELECT * FROM courseposter");  
           
             
              while(r.next()){
                     
                     Vector vec=new Vector();
                     
                     String studentid =(r.getString("studentid"));
                     String nic=(r.getString("nic"));
                     String fullname=(r.getString("Fullname"));
                     String initial=(r.getString("initials"));
                     String course=(r.getString("course"));
                     String duration=(r.getString("duration"));
                     String batchno=(r.getString("batchno"));
                     String day=(r.getString("day"));
                     String coursefee=(r.getString("coursefee"));
                     
                     
                     vec.add(studentid);
                     vec.add(nic);
                     vec.add(fullname);
                     vec.add(initial);
                     vec.add(course);
                     vec.add(duration);
                     vec.add(batchno);
                     vec.add(day);
                     vec.add(coursefee);
                    
                  tb.addRow(vec);
              }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    
    
    
    }
    
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo batch;
    private datechooser.beans.DateChooserCombo batch1;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField initial;
    private javax.swing.JTextField initial1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3save;
    private javax.swing.JButton jButton3save1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCombobatch;
    private javax.swing.JComboBox<String> jCombobatch1;
    private javax.swing.JComboBox<String> jCombocourse;
    private javax.swing.JComboBox<String> jCombocourse1;
    private javax.swing.JComboBox<String> jComboduration;
    private javax.swing.JComboBox<String> jComboduration1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField nic1;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField studentid1;
    private javax.swing.JTextField ugraduatefee;
    private javax.swing.JTextField ugraduatefee1;
    // End of variables declaration//GEN-END:variables

    private TableModel ToTableModel(ResultSet rs) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
