/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class RegistrationTeacher extends javax.swing.JPanel {
Connection con;
    
    String gender;
String filename = null;
byte[] person_image = null;
  
    /**
 ng    *
     * Creates new form Newstudent
     */
    public RegistrationTeacher() {
        initComponents();
        DBconnection c=new DBconnection();
        con= c.getconnection();
         teacherInfo();
        
        
    
        
    }
    
    
    public void clear(){
    firstname.setText("");
    lname.setText("");
    fullname.setText("");
    initial.setText("");
    dateChooserCombo1.setText("");
    nic.setText("");
 
    
    contact.setText("");
    email.setText("");
     picture.setIcon(null);
     jComboBox2.setSelectedItem("None");
     jTextField1.setText("");
     ID.setText("");
     
        
    
    
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable1 = new javax.swing.JTable();
        email = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        initial = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        picture = new javax.swing.JLabel();
        jButton3save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        initial1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        picture1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mytable1.setBackground(new java.awt.Color(255, 255, 255));
        mytable1.setForeground(new java.awt.Color(102, 102, 102));
        mytable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID##", "Title", "Fname", "Lname", "full Name", "Other Name", "date", "NID/Passport", "Gender", "Contact", "E-Mail", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mytable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mytable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mytable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1090, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1110, 210));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 240, 30));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 240, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("               E-Mail");
        jLabel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 280, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("      Contact Number");
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 280, 30));

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 240, 30));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(0, 0, 0));
        male.setText("Male");
        male.setToolTipText("");
        male.setOpaque(false);
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 110, 30));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(0, 0, 0));
        female.setText("Female");
        female.setOpaque(false);
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 130, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("                 Gender");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 280, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("      NID/Passport Numb");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 280, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("First Name");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 30));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 240, 30));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 240, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Last Name");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, 30));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Mr.", "Mrs.", "Miss" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 240, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Title");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("                 RegistrationTeacher");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 590, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Full Name");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 30));

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel3.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, 30));

        initial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialActionPerformed(evt);
            }
        });
        jPanel3.add(initial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 240, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Other Name");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("   Date Of Birth");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Browse");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        picture.setBackground(new java.awt.Color(0, 153, 153));
        picture.setOpaque(true);
        jPanel3.add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 250));

        jButton3save.setBackground(new java.awt.Color(255, 255, 255));
        jButton3save.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3save.setForeground(new java.awt.Color(0, 153, 153));
        jButton3save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Save-as-icon.png"))); // NOI18N
        jButton3save.setMnemonic('[');
        jButton3save.setText("Save");
        jButton3save.setAutoscrolls(true);
        jButton3save.setOpaque(false);
        jButton3save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3saveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3save, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 170, 60));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Text-Edit-icon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 170, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 180, 60));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project icon/Close-2-icon.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 210, 60));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 240, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Full Name");
        jLabel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 30));

        fullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname1ActionPerformed(evt);
            }
        });
        jPanel4.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, 30));

        initial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initial1ActionPerformed(evt);
            }
        });
        jPanel4.add(initial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 240, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Other Name");
        jLabel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("   Date Of Birth");
        jLabel36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("Browse");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        picture1.setBackground(new java.awt.Color(0, 153, 153));
        picture1.setOpaque(true);
        jPanel4.add(picture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 150));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("   Type  ID## to Delete or Search ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 30));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("                  ID##");
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 550, 250));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3saveActionPerformed

        try {
            
           
            if (ID.getText().isEmpty() |firstname.getText().isEmpty() | lname.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|dateChooserCombo1.getText().isEmpty()|nic.getText().isEmpty()|contact.getText().isEmpty()|email.getText().isEmpty()|jComboBox2.getSelectedItem().equals("None")) {
               
                 getToolkit().beep();
                JOptionPane.showMessageDialog(null,"One of the required field is empty!","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
            else if (person_image!=null) {
           
            String query = "INSERT INTO teacherInfo (ID,title,fname,lname,fullname,initial,dob,nic,gender,contact,email,image) values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, ID.getText());
             pst.setString(2, jComboBox2.getSelectedItem().toString());
            pst.setString(3, firstname.getText());
            pst.setString(4, lname.getText());
            pst.setString(5, fullname.getText());
            pst.setString(6, initial.getText());
            pst.setString(7, dateChooserCombo1.getText());
            pst.setString(8, nic.getText());
            if (male.isSelected()) {
                gender = "Male";
            }
            if (female.isSelected()) {
                gender = "Female";
            }
            pst.setString(9, gender);
            pst.setString(10, contact.getText());
            pst.setString(11, email.getText());
            pst.setBytes(12, person_image);
            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)mytable1.getModel();
            model.setRowCount(0);
            teacherInfo();
            
            JOptionPane.showMessageDialog(null, "Saved Successfully");

            }

            else{
            getToolkit().beep();
                JOptionPane.showMessageDialog(null,"You cannot save data without a Teacher image","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
           


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
//////////////////////////////////////////////////////////////
     //   try {
            
          // DefaultTableModel model=(DefaultTableModel)mytable.getModel();
          // model.fireTableDataChanged();
          
          //  if ( ID.getText().isEmpty() | firstname.getText().isEmpty() | lname.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|dateChooserCombo1.getText().isEmpty()|nic.getText().isEmpty()|contact.getText().isEmpty()|email.getText().isEmpty()|jComboBox2.getSelectedItem().equals("None")) {
               
               //  getToolkit().beep();
              //  JOptionPane.showMessageDialog(null,"One of the required field is empty!","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
          //  }
           // else if (person_image!=null) {
             /*   if (male.isSelected()) {
                gender = "Male";
            }
            if (female.isSelected()) {
                gender = "Female";
            }
           
            
         /*   String query = "INSERT INTO student (ID,title,fname,lname,fullname,initial,dob,nic,gender,contact,email,image) values('"+ID.getText()+"','"+jComboBox2.getSelectedItem().toString()+"','"+firstname.getText()+"','"+lname.getText()+"','"+fullname.getText()+"','"+initial.getText()+"','"+dateChooserCombo1.getText()+"','"+nic.getText()+"','"+gender+"','"+contact.getText()+"','"+email.getText()+"', '"+person_image+"')";
           PreparedStatement pst = con.prepareStatement(query);
           Statement smt=con.createStatement();
           int rowinserted=smt.executeUpdate(query);
            DefaultTableModel model=(DefaultTableModel)mytable.getModel();
            model.fireTableDataChanged();
            model.setRowCount(0);
            Studentinfo();
            
            if(rowinserted > 0 )
            {
            JOptionPane.showMessageDialog(null,"Data inserted Successfully");
            
            }
  */
           
           //int rowinserted=pst.executeUpdate(query);
                      
           // model.setRowCount(0);
            /*if(rowinserted > 0 )
            {
            JOptionPane.showMessageDialog(null,"Data dddddddddddddddddddddddddddddddddddddddd Successfully");
            
            }*/

           /*
         
   
            pst.setString(1, jComboBox2.getSelectedItem().toString());
            pst.setString(2, firstname.getText());
            pst.setString(3, lname.getText());
            pst.setString(4, fullname.getText());
            pst.setString(5, initial.getText());
            pst.setString(6, dateofbirth.getText());
            pst.setString(7, nic.getText());
            if (male.isSelected()) {
                gender = "Male";
            }
            if (female.isSelected()) {
                gender = "Female";
            }
            pst.setString(8, gender);
            pst.setString(9, contact.getText());
            pst.setString(10, email.getText());
            
            pst.setBytes(11, person_image);
            pst.executeUpdate();
           */
            
            //JOptionPane.showMessageDialog(null, "Saved Successfully");

            //}
/*
            else{
            getToolkit().beep();
                JOptionPane.showMessageDialog(null,"You cannot save data without a student image","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
           
*/
/*
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        */
        //clear();
        
        //////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jButton3saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (ID.getText().isEmpty() |  firstname.getText().isEmpty() | lname.getText().isEmpty()| fullname.getText().isEmpty()|initial.getText().isEmpty()|dateChooserCombo1.getText().isEmpty()|nic.getText().isEmpty()|contact.getText().isEmpty()|email.getText().isEmpty()|jComboBox2.getSelectedItem().equals("None")) {
             getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Specify What Data You Want To Update","ERROR",JOptionPane.ERROR_MESSAGE,null);
        }
        else{
       
        try {
           
            

            String value=ID.getText();
            String query="";
           
             
              if (person_image!=null) {
                query = "UPDATE teacherInfo SET title=?,fname=?,lname=?,fullname=?,initial=?,dob=?,nic=?,gender=?,contact=?,email=?,image=? WHERE ID='"+value+"'";
            }else{
              
              query = "UPDATE teacherInfo SET title=?,fname=?,lname=?,fullname=?,initial=?,dob=?,nic=?,gender=?,contact=?,email=? WHERE ID='"+value+"'";
              
              
              }
      
                    

            PreparedStatement pst = con.prepareStatement(query);

           pst.setString(1, jComboBox2.getSelectedItem().toString());
           pst.setString(2, firstname.getText());
            pst.setString(3, lname.getText());
            pst.setString(4, fullname.getText());
            pst.setString(5, initial.getText());

            pst.setString(6, dateChooserCombo1.getText());
             pst.setString(7, nic.getText());
            if (male.isSelected()) {
                gender="Male";
            }if (female.isSelected()) {
                gender="Female";
            }
            pst.setString(8, gender);
            
//            pst.setString(8, mobilenumber.getText());
     //       pst.setString(9, homenumber.getText());
     pst.setString(9, contact.getText());
            pst.setString(10, email.getText());
            if (person_image!=null) {
                pst.setBytes(11, person_image);
                
            }
           //  pst.setString(11, ID.getText());
            

            pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)mytable1.getModel();
            model.setRowCount(0);
          teacherInfo();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
            
            
            
     
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
          clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
            
            if (ID.getText().isEmpty()) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Please Enter the ID## in the Search Field to delete data","ERROR",JOptionPane.ERROR_MESSAGE,null);
                
            }
            else{
            
            
            getToolkit().beep();
             int p= JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Teacher "+fullname.getText()+" From The database","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0) {
            
            String query = "DELETE FROM teacherInfo WHERE ID='"+ID.getText()+"'";
            //String query2 = "DELETE FROM courseposter WHERE ID=?";
            //String query3 = "DELETE FROM courseunder WHERE ID=?";
            Statement smt=con.createStatement();
            int rowinserted=smt.executeUpdate(query);
            DefaultTableModel model=(DefaultTableModel)mytable1.getModel();
            model.fireTableDataChanged();
            model.setRowCount(0);
            teacherInfo();
           // PreparedStatement pst = con.prepareStatement(query);
            //String query2 = "DELETE FROM courseposter WHERE nic=?";
           // PreparedStatement pst2 = con.prepareStatement(query2);
           // //String query3 = "DELETE FROM courseunder WHERE nic=?";
           // PreparedStatement pst3 = con.prepareStatement(query3);
           // pst.setString(1, jTextField1.getText());
           // pst.execute();
           // pst2.setString(1, jTextField1.getText());
           // pst2.execute();
            // pst3.setString(1, jTextField1.getText());
           // pst3.execute();
             if(rowinserted > 0 )
            {
            //JOptionPane.showMessageDialog(null,"Data bbbbb Successfully");
                JOptionPane.showMessageDialog(null, "data successfully deleted");
                 clear();
            
        }
            
        }
            
            
            
          
            
            }
            
        
         
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
        

            String query="SELECT * FROM teacherInfo WHERE ID=?";
            PreparedStatement pst= con.prepareStatement(query);
            pst.setString(1,jTextField1.getText());
            //pst.setString(2, jTextField1.getText());
            ResultSet rs=pst.executeQuery();
            if (rs.next()) {
                String add=rs.getString("ID");
                ID.setText(add);
                 String add1=rs.getString("title");
                jComboBox2.setSelectedItem(add1);
                String add2=rs.getString("fname");
                firstname.setText(add2);
                String add3=rs.getString("lname");
                lname.setText(add3);
                String add4=rs.getString("fullname");
                fullname.setText(add4);
                String add5=rs.getString("initial");
                initial.setText(add5);
                 String add6=rs.getString("dob");
                dateChooserCombo1.setText(add6);
                String add7=rs.getString("nic");
                nic.setText(add7);
                
                String gender = rs.getString("gender");

                if (gender.equals("Male"))
                {
                    male.setSelected(true);

                }
                else if(gender.equals("Female"))
                {
                    female.setSelected(true);
                }

                
                String add9=rs.getString("contact");
                contact.setText(add9);
               
                String add10=rs.getString("email");
                email.setText(add10);

              
                byte[] img = rs.getBytes("image");
                
                //Resize The ImageIcon
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(picture.getWidth(), picture.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                picture.setIcon(newImage);
               
            }

         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
         if(!Pattern.matches("^[a-zA-Z0-9]+[@](1)+[a-zA-Z0-9]+[.](1)+[a-zA-Z0-9]+$",email.getText())) {
            JOptionPane.showMessageDialog(null," please inter a valid email","error",JOptionPane.ERROR_MESSAGE);
        } else {
                        JOptionPane.showMessageDialog(null," valid email","GOOD",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void initialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          JFileChooser chooser = new JFileChooser();
        
        
        
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
         filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(picture.getWidth(), picture.getHeight(), Image.SCALE_SMOOTH));
        picture.setIcon(imageicon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(f);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readnum; (readnum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readnum);

            }
                  person_image = bos.toByteArray();
        } catch (Exception e) {
        }
       

    }//GEN-LAST:event_jButton5ActionPerformed

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
      
        String s=nic.getText();
            
            if (!(s.length()<10 ))
            {
                
                    evt.consume();
                      getToolkit().beep();
            
            }
    }//GEN-LAST:event_nicKeyTyped

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c=evt.getKeyChar();
        if (! (Character.isDigit(c))||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE) {
            
            evt.consume();
            getToolkit().beep();
        }
        String s=contact.getText();
            
            if (!(s.length()<10 ))
            {
            getToolkit().beep();
            evt.consume();
            }
            
    }//GEN-LAST:event_contactKeyTyped

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
//      if(!(nic.getText().trim().matches("^[0-9]{9}[vVxX]$")))
//{
//    
//}
//      else{
//      nic.setBackground(Color.red);
//      
//      
//      
//      }  
//     
       
    }//GEN-LAST:event_nicKeyReleased

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void mytable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mytable1MouseClicked
    // TODO add your handling code here:
   /* DefaultTableModel model = (DefaultTableModel)mytable1.getModel();
    int selectedrow=mytable1.getSelectedRow();
    ID.setText(model.getValueAt(selectedrow, 0).toString());
    jComboBox2.setSelectedItem(model.getValueAt(selectedrow,1).toString());
    firstname.setText(model.getValueAt(selectedrow, 2).toString());
    lname.setText(model.getValueAt(selectedrow, 3).toString());
    fullname.setText(model.getValueAt(selectedrow,4).toString());
    initial.setText(model.getValueAt(selectedrow, 5).toString());
    gender.equals(model.getValueAt(selectedrow, 6).toString());
    nic.setText(model.getValueAt(selectedrow,7).toString());
    dateChooserCombo1.setText(model.getValueAt(selectedrow, 8).toString());
    contact.setText(model.getValueAt(selectedrow,9).toString());
    email.setText(model.getValueAt(selectedrow, 10).toString());
    person_image.equals(model.getValueAt(selectedrow, 11).toString());
    
        */
    }//GEN-LAST:event_mytable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void fullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullname1ActionPerformed

    private void initial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initial1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    
    
    
    
    
    
    /////////////////
    
    
    
     public void Studentinfo()
     {
  
     
    
    
     
     }
     
     
     
             public void teacherInfo()
    {
        try {
            
            String qury="SELECT * FROM teacherInfo ";
             Statement st=con.createStatement();
            DefaultTableModel tb=(DefaultTableModel)mytable1.getModel();
            tb.fireTableDataChanged();
             //tb.setRowCount(0);
             
        //  int rowinserted=st.executeUpdate(qury);
            
             ResultSet r=st.executeQuery(qury);  
              
                          while(r.next()){
                     
                     Vector v=new Vector();
                      String ID =(r.getString("ID"));
                     String title =(r.getString("title"));
                     String fname=(r.getString("fname"));
                     String lname=(r.getString("lname"));
                     String fullname=(r.getString("fullname"));
                     String initial=(r.getString("initial"));
                     String dob=(r.getString("dob"));
                     String nic=(r.getString("nic"));
                     String gender=(r.getString("gender"));
                     String contact=(r.getString("contact"));
                     String email=(r.getString("email"));
                     String image=(r.getString("image"));
                     
                   
                    
                
      //setBytes(10, person_image));
                     
                     v.add(ID);
                     v.add(title);
                     v.add(fname);
                     v.add(lname);
                     v.add(fullname);
                     v.add(initial);
                     v.add(dob);
                     v.add(nic);
                     v.add(gender);
                     v.add(contact);
                     v.add(email);
                      v.add(image);
                     //hari bn
                     
                     
                     tb.addRow(v);
              }
            
        } catch (Exception e) {
        }
    
    } 
    ///////////************
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField initial;
    private javax.swing.JTextField initial1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3save;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTable mytable1;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel picture1;
    // End of variables declaration//GEN-END:variables



}
